/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pierce_multipthread_PThread */

#ifndef _Included_com_pierce_multipthread_PThread
#define _Included_com_pierce_multipthread_PThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pierce_multipthread_PThread
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pierce_multipthread_PThread_init
  (JNIEnv *, jobject);

/*
 * Class:     com_pierce_multipthread_PThread
 * Method:    pthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pierce_multipthread_PThread_pthread
  (JNIEnv *, jobject);

/*
 * Class:     com_pierce_multipthread_PThread
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pierce_multipthread_PThread_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
